Repository Compete-McGill/wisp-ui, pull requests merged in 2020-05, with the labels that each got.

#1 Features/placeholder pages
  public/index.html
  src/App.vue
  src/components/Dashboard/Problem.vue
  src/components/Dashboard/ProblemSet.vue
  src/components/Dashboard/Stats.vue
  src/components/Home/Announcement.vue
  src/components/Home/HelloWorld.vue
  src/components/Home/News.vue
  src/components/ProblemSets/Index/ProblemSet.vue
  src/components/ProblemSets/Show/ProblemInfo.vue
  src/components/ProblemSets/Show/ProblemSetInfo.vue
  src/components/Shared/Logo.vue
  src/components/Shared/NavBar.vue
  src/plugins/vuetify.js
  src/router/index.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  src/views/About/index.vue
  src/views/Dashboard/index.vue
  src/views/Home/index.vue
  src/views/Login/index.vue
  src/views/ProblemSets/Index/index.vue
  src/views/ProblemSets/Show/index.vue
  src/views/Problems/Index/index.vue
  src/views/Problems/Show/index.vue
  src/views/Profile/index.vue
  src/views/Settings/index.vue
  src/views/SignUp/index.vue
  vue.config.js
Labels: enhancement

#2 Implemented login view
  src/App.vue
  src/components/Shared/NavBar.vue
  src/router/index.js
  src/store/actions.js
  src/store/mutations.js
  src/views/Login/index.vue
Labels: enhancement

#5 Features/problem sets view
  package-lock.json
  package.json
  src/App.vue
  src/components/Dashboard/ProblemSet.vue
  src/components/ProblemSets/Index/ProblemSet.vue
  src/components/ProblemSets/Show/ProblemInfo.vue
  src/components/ProblemSets/Show/ProblemSetInfo.vue
  src/components/Shared/NavBar.vue
  src/gateways/wisp-api.js
  src/router/index.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  src/views/Dashboard/index.vue
  src/views/Login/index.vue
  src/views/ProblemSets/Index/index.vue
  src/views/ProblemSets/Show/index.vue
Labels: enhancement

#7 Features/problem sets view
  src/App.vue
  src/components/Dashboard/ProblemSet.vue
  src/components/ProblemSets/Index/ProblemSet.vue
  src/components/ProblemSets/Show/ProblemInfo.vue
  src/components/ProblemSets/Show/ProblemSetInfo.vue
  src/gateways/wisp-api.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  src/views/Login/index.vue
  src/views/ProblemSets/Index/index.vue
  src/views/ProblemSets/Show/index.vue
Labels: enhancement

#10 Bugfixes/style dashboard
  src/App.vue
  src/components/Dashboard/Problem.vue
  src/components/Dashboard/ProblemSet.vue
  src/components/ProblemSets/Index/ProblemSet.vue
  src/components/ProblemSets/Show/ProblemInfo.vue
  src/components/ProblemSets/Show/ProblemSetInfo.vue
  src/views/Dashboard/index.vue
  src/views/Login/index.vue
  src/views/ProblemSets/Show/index.vue
Labels: bug

#12 Added profile page
  src/views/Profile/index.vue
  src/views/Settings/index.vue
Labels: enhancement

#16 0.1.0
  .github/workflows/dockerhub.yaml
  package-lock.json
  package.json
  public/img/icons/cplogo.svg
  public/index.html
  src/App.vue
  src/assets/cp-acmwin.jpg
  src/assets/cp-csgames.jpg
  src/assets/cp-together.jpg
  src/assets/cp-workshop.jpg
  src/components/Dashboard/Problem.vue
  src/components/Dashboard/ProblemSet.vue
  src/components/Home/Announcement.vue
  src/components/ProblemSets/Index/ProblemSet.vue
  src/components/ProblemSets/Show/ProblemInfo.vue
  src/components/ProblemSets/Show/ProblemSetInfo.vue
  src/components/Shared/NavBar.vue
  src/gateways/wisp-api.js
  src/router/index.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  src/views/About/index.vue
  src/views/Dashboard/index.vue
  src/views/Home/index.vue
  src/views/Login/index.vue
  src/views/ProblemSets/Index/index.vue
  src/views/ProblemSets/Show/index.vue
  src/views/Problems/Index/index.vue
  src/views/Profile/index.vue
  src/views/Settings/index.vue
  src/views/SignUp/index.vue
Labels: enhancement

#17 Bugfixes/package dependencies
  package.json
Labels: bug

#19 Login redirect waits for global data fetch
  src/App.vue
  src/views/Login/index.vue
Labels: bug

#28 Fixed merge conflict errors
  src/views/Dashboard/index.vue
  src/views/Problems/Index/index.vue
Labels: bug

#30 Features/profile update dialog
  src/views/Profile/index.vue
Labels: enhancement

#31 Changed wisp-api gateway
  src/gateways/wisp-api.js
Labels: bug

#32 0.1.4
  src/gateways/wisp-api.js
  src/views/Profile/index.vue
Labels: bug, enhancement

#34 Features/stats card
  package-lock.json
  package.json
  src/App.vue
  src/components/Dashboard/Stats.vue
  src/views/ProblemSets/Index/index.vue
  src/views/Problems/Index/index.vue
Labels: bug, enhancement

#35 Bugs/#21 mobile compatibility
  src/components/Dashboard/Stats.vue
  src/components/Shared/NavBar.vue
Labels: bug

#37 Improvements/update forms and fonts
  src/components/Home/Announcement.vue
  src/components/Shared/NavBar.vue
  src/gateways/wisp-api.js
  src/views/Profile/index.vue
  src/views/SignUp/index.vue
Labels: bug

#40 0.1.5
  package-lock.json
  package.json
  src/App.vue
  src/components/Dashboard/Stats.vue
  src/components/Home/Announcement.vue
  src/components/Shared/NavBar.vue
  src/gateways/wisp-api.js
  src/views/ProblemSets/Index/index.vue
  src/views/Problems/Index/index.vue
  src/views/Profile/index.vue
  src/views/SignUp/index.vue
Labels: bug

#41 Separated pipeline to dev and prod
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  Dockerfile
Labels: enhancement

#42 Features/improve pipeline
  .github/workflows/dev.yaml
Labels: bug

#39 Update Site Typography, Description and Timeline Effects
  src/components/Home/Announcement.vue
  src/views/About/index.vue
  src/views/Admin/index.vue
  src/views/Dashboard/index.vue
  src/views/Home/index.vue
  src/views/Login/index.vue
  src/views/ProblemSets/Index/index.vue
  src/views/Problems/Index/index.vue
  src/views/Profile/index.vue
  src/views/Settings/index.vue
  src/views/SignUp/index.vue
Labels: enhancement

#55 Update Font on Problem Set View
  src/views/ProblemSets/Show/index.vue
Labels: bug

#60 Fix for user data not reloading on refresh
  src/App.vue
Labels: bug

#61 Fix for user data not reloading on refresh (#60)
  src/App.vue
Labels: bug

#62 Implemented caching with webpack
  public/index.html
  vue.config.js
Labels: enhancement

#63 Update vue.config.js file
  vue.config.js
Labels: bug
